## WARNING -- this is TOTALLY out of date

# it needs to be completely replaced with a
# modern version built on the scikit-build system

package:
  name: py_gnome
  version: 0.1.1

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - netcdf4
    - cython
  run:
    - adios_db
    - python
    - pytest
    - scipy
    - numpy
    - netcdf4
    - colander
    - pil
    - pyzmq
    - repoze.lru
    - six
    - geojson


about:
  home: https://github.com/NOAA-ORR-ERD/PyGnome
  license: Public Domain

