package:
  name: zope.sqlalchemy
  version: "0.7.5"

source:
  fn: zope.sqlalchemy-0.7.5.zip
  url: https://pypi.python.org/packages/source/z/zope.sqlalchemy/zope.sqlalchemy-0.7.5.zip
  md5: 0a468bd5b8884cd29fb71acbf7eaa31e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.sqlalchemy = zope.sqlalchemy:main
    #
    # Would create an entry point called zope.sqlalchemy that calls zope.sqlalchemy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sqlalchemy >=0.5.1
    - transaction
    - zope.interface >=3.6.0

  run:
    - python
    - setuptools
    - sqlalchemy >=0.5.1
    - transaction
    - zope.interface >=3.6.0

test:
  # Python imports
  imports:
    - zope
    - zope.sqlalchemy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.sqlalchemy
  license: Zope Public License
  summary: 'Minimal Zope/SQLAlchemy transaction integration'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
