# new CI using pixi to run tests, etc.
# Also -- we don't need to build docker images here anymore
# just wheels
# and hopefully conda pacakges before too long

variables:
  IMAGE_NAME: 'registry.orr.noaa.gov/erd/environments/ubuntu-pixi:latest'
  GIT_DEPTH: 2

stages:
  - lint
  - test
  - build

default:
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install git g++ make libxext-dev libsm-dev libxrender-dev -y

lint_pygnome:
  stage: lint
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run lint

test_pygnome:
  stage: test
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run test


test_pygnome_windows:
  stage: test
  allow_failure: false
  before_script: [] # so it won't try to install the linux stuff
  tags:
    - windows-build-image-2026
  script:
    - cd py_gnome
    - pixi run test

run_example_scripts:
  stage: test
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run run_example_scripts

run_testing_scripts:
  stage: test
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run run_testing_scripts

test_multi_py:
  stage: test
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run -e test312 test
    - pixi run -e test313 test

build_wheels:
  stage: build
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run -e build312 build_wheel
    - pixi run -e build313 build_wheel

build_wheels_windows:
  stage: build
  allow_failure: false
  before_script: [] # so it won't try to install the linux stuff
  tags:
    - windows-build-image-2026
  script:
    - cd py_gnome
    - pixi run -e build312 build_wheel
    - pixi run -e build313 build_wheel


build_docs:
  stage: build
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run build_docs

# Old setup -- way more complicated!

# # All the scripts in "input_file_examples" should run without errors,
# # But once in a while we refactor something that breaks something.
# test_pygnome_input_file_examples:
#   stage: test
#   tags:
#     - docker
#   allow_failure: true
#   image: $CI_REGISTRY$IMAGE_NAME$PYTHON_VER
#   script:
#     - cd ./py_gnome/scripts/input_file_examples && python run_all.py 2<&1

# # make sure the example scripts run without error
# # this can fail, but we want to be warned ...
# test_pygnome_example_scripts:
#   stage: test
#   tags:
#     - docker
#   allow_failure: true
#   image: $CI_REGISTRY$IMAGE_NAME$PYTHON_VER
#   script:
#     - cd ./py_gnome/scripts/example_scripts && python run_all.py 2<&1
