# new CI using pixi to run tests, etc.
# Also -- we don't need to build docker images here anymore
# just wheels
# and hopefully conda pacakges before too long

variables:
  IMAGE_NAME: 'registry.orr.noaa.gov/erd/environments/ubuntu-pixi:latest'
  GIT_DEPTH: 2

stages:
  - test_code
  - test_wheels
  - build

default:
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install git g++ make libxext-dev libsm-dev libxrender-dev -y

test_dev:
  stage: test_code
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run test

lint_pygnome:
  stage: test_code
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run lint

run_example_scripts:
  stage: test_code
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run run_example_scripts

run_testing_scripts:
  stage: test_code
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run run_testing_scripts

run_input_file_examples:
  stage: test_code
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run run_input_file_examples

test_pygnome_windows:
  stage: test_code
  allow_failure: false
  before_script: [] # so it won't try to install the linux stuff
  tags:
    - windows-build-image-2026
  script:
    - cd py_gnome
    - pixi run test

test_wheels_multi_py:
  stage: test_wheels
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run -e test312 test_wheel
    - pixi run -e test313 test_wheel

build_wheels:
  stage: build
  allow_failure: false
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run -e build312 build_wheel
    - pixi run -e build313 build_wheel

build_wheels_windows:
  stage: build
  allow_failure: false
  before_script: [] # so it won't try to install the linux stuff
  tags:
    - windows-build-image-2026
  script:
    - cd py_gnome
    - pixi run -e build312 build_wheel
    - pixi run -e build313 build_wheel


build_docs:
  stage: build
  allow_failure: true
  image: $IMAGE_NAME
  script:
    - cd py_gnome
    - pixi run build_docs
