package:
  name: geojson
  version: "1.0.9"

source:
  fn: geojson-1.0.9.tar.gz
  url: https://pypi.python.org/packages/source/g/geojson/geojson-1.0.9.tar.gz
  md5: 94880d993dba8b184de122c5a84fa329
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - geojson = geojson:main
    #
    # Would create an entry point called geojson that calls geojson.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - geojson

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD License
  summary: 'Python bindings and utilities for GeoJSON'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
