"""CAMEO Chemicals data that is not in the database.
"""


# Reactivity hazard phrases
# {hazard_code : list of phrase strings}
HAZARD_PHRASES = {
   'A1': ['Explosive'],
   'A2': ['Explosive'],
   'A3': ['Explosive'],
   'A4': ['Explosive'],
   'A5': ['Explosive'],
   'A6': ['Explosive'],
   'A8': ['Explosive'],
   'A9': ['Explosive'],
   'A10': ['Explosive'],
   'B1': ['Flammable'],
   'B3': ['Flammable'],
   'B4': ['Flammable'],
   'B5': ['Flammable gas'],
   'B6': ['Flammable gas', 'Toxic gas'],
   'C': ['Heat generation'],
   'D1': ['Heat generation', 'Polymerization'],
   'D3': ['Toxic gas'],
   'D4': ['Nonflammable, nontoxic gas'],
   'D5': ['Combustion-enhancing gas'],
   'D6': ['Heat generation', 'Toxic gas', 'Corrosive'],
   'D7': ['Corrosive'],
   'E': ['Toxic'],
   'F': ['Unknown'],
   'G': ['Intense reaction'],
   'H': ['Radiation'],
   'I': []	# no phrase for this code
    }

UNNA_GUIDE_NAMES = {
    # Guide number : guide name
   '111': 'Mixed Load / Unidentified Cargo',
   '112': 'Explosives* - Division 1.1, 1.2, 1.3, 1.5 or 1.6; Class A or B',
   '113': 'Flammable Solids - Toxic (Wet/Desensitized Explosive)',
   '114': 'Explosives* - Division 1.4; Class C',
   '115': 'Gases - Flammable (Including Refrigerated Liquids)',
   '116': 'Gases - Flammable (Unstable)',
   '117': 'Gases - Toxic - Flammable (Extreme Hazard)',
   '118': 'Gases - Flammable - Corrosive',
   '119': 'Gases - Toxic - Flammable',
   '120': 'Gases - Inert (Including Refrigerated Liquids)',
   '121': 'Gases - Inert',
   '122': 'Gases - Oxidizing (Including Refrigerated Liquids)',
   '123': 'Gases - Toxic and/or Corrosive',
   '124': 'Gases - Toxic and/or Corrosive - Oxidizing',
   '125': 'Gases - Corrosive',
   '126': 'Gases - Compressed or Liquefied (Including Refrigerant Gases)',
   '127': 'Flammable Liquids (Polar / Water-Miscible)',
   '128': 'Flammable Liquids (Non-Polar / Water-Immiscible)',
   '129': 'Flammable Liquids (Polar / Water-Miscible / Noxious)',
   '130': 'Flammable Liquids (Non-Polar / Water-Immiscible / Noxious)',
   '131': 'Flammable Liquids - Toxic',
   '132': 'Flammable Liquids - Corrosive',
   '133': 'Flammable Solids',
   '134': 'Flammable Solids - Toxic and/or Corrosive',
   '135': 'Substances - Spontaneously Combustible',
   '136': 'Substances - Spontaneously Combustible - Toxic and/or Corrosive (Air-Reactive)',
   '137': 'Substances - Water-Reactive - Corrosive',
   '138': 'Substances - Water-Reactive (Emitting Flammable Gases)',
   '139': 'Substances - Water-Reactive (Emitting Flammable and Toxic Gases)',
   '140': 'Oxidizers',
   '141': 'Oxidizers - Toxic',
   '142': 'Oxidizers - Toxic (Liquid)',
   '143': 'Oxidizers (Unstable)',
   '144': 'Oxidizers (Water-Reactive)',
   '145': 'Organic Peroxides (Heat and Contamination Sensitive)',
   '146': 'Organic Peroxides (Heat, Contamination and Friction Sensitive)',
   '147': 'Lithium Ion Batteries',
   '148': 'Organic Peroxides (Heat and Contamination Sensitive / Temperature Controlled)',
   '149': 'Substances (Self-Reactive)',
   '150': 'Substances (Self-Reactive / Temperature Controlled)',
   '151': 'Substances - Toxic (Non-Combustible)',
   '152': 'Substances - Toxic (Combustible)',
   '153': 'Substances - Toxic and/or Corrosive (Combustible)',
   '154': 'Substances - Toxic and/or Corrosive (Non-Combustible)',
   '155': 'Substances - Toxic and/or Corrosive (Flammable / Water-Sensitive)',
   '156': 'Substances - Toxic and/or Corrosive (Combustible / Water-Sensitive)',
   '157': 'Substances - Toxic and/or Corrosive (Non-Combustible / Water-Sensitive)',
   '158': 'Infectious Substances',
   '159': 'Substances (Irritating)',
   '160': 'Halogenated Solvents',
   '161': 'Radioactive Materials (Low Level Radiation)',
   '162': 'Radioactive Materials (Low to Moderate Level Radiation)',
   '163': 'Radioactive Materials (Low to High Level Radiation)',
   '164': 'Radioactive Materials (Special Form / Low to High Level External Radiation)',
   '165': 'Radioactive Materials (Fissile / Low to High Level Radiation)',
   '166': 'Radioactive Materials - Corrosive (Uranium Hexafluoride / Water-Sensitive)',
   '167': 'Fluorine (Refrigerated Liquid)',
   '168': 'Carbon Monoxide (Refrigerated Liquid)',
   '169': 'Aluminum (Molten)',
   '170': 'Metals (Powders, Dusts, Shavings, Borings, Turnings, or Cuttings, Etc.)',
   '171': 'Substances (Low to Moderate Hazard)',
   '172': 'Gallium and Mercury'
    }

UNNA_LABEL_NAMES = {
    # Label number (string) : label name 
   '1.1': '1.1 - Explosives (with a mass explosion hazard)',
   '1.2': '1.2 - Explosives (with a projection hazard)',
   '1.3': '1.3 - Explosives (with predominately a fire hazard)',
   '1.4': '1.4 - Explosives (with no significant blast hazard)',
   '1.5': '1.5 - Very insensitive explosives; blasting agents',
   '1.6': '1.6 - Extremely insensitive detonating substances',
   '2.1': '2.1 - Flammable gas',
   '2.2': '2.2 - Non-flammable compressed gas',
   '2.2_Ox': '2.2 - Oxygen',
   '2.3': '2.3 - Poisonous gas',
   '3': '3 - Flammable liquid',
   '3.0_CL': '3 - Combustible liquid (U.S.)',
   '4.1': '4.1 - Flammable solid',
   '4.2': '4.2 - Spontaneously combustible material',
   '4.3': '4.3 - Dangerous when wet material',
   '5.1': '5.1 - Oxidizer',
   '5.2': '5.2 - Organic peroxide',
   '6.1': '6.1 - Poisonous materials',
   '6.2': '6.2 - Infectious substances (Etiologic agent)',
   '7': '7 - Radioactive material',
   '8': '8 - Corrosive material',
   '9': '9 - Miscellaneous hazardous material',
   '1005': 'UN/NA number 1005 (Ammonia, Anhydrous)',
    }

UNNA_EXPLOSIVE_CODES = {
    # Code (string) : title
   'A': 'Substances which are expected to mass detonate very soon after fire reaches them.',
   'B': 'Articles which are expected to mass detonate very soon after fire reaches them.',
   'C': 'Substances or articles which may be readily ignited and burn violently without necessarily exploding.',
   'D': 'Substances or articles which may mass detonate (with blast and/or fragment hazard) when exposed to fire.',
   'E': 'Articles which may mass detonate in a fire.',
   'F': 'Articles which may mass detonate in a fire.',
   'G': 'Substances and articles which may mass explode and give off smoke or toxic gases.',
   'H': 'Articles which in a fire may eject hazardous projectiles and dense white smoke.',
   'J': 'Articles which may mass explode.',
   'K': 'Articles which in a fire may eject hazardous projectiles and toxic gases.',
   'L': 'Substances and articles which present a special risk and could be activated by exposure to air or water.',
   'N': 'Articles which contain only extremely insensitive detonating substances and demonstrate a negligible probability of accidental ignition or propagation.',
   'S': 'Packaged substances or articles which, if accidently initiated, produce effects that are usually confined to the immediate vicinity.'
    }




