package:
  name: awesome-slugify
  version: !!str 1.6

source:
  fn: awesome-slugify-1.6.tar.gz
  url: https://pypi.python.org/packages/source/a/awesome-slugify/awesome-slugify-1.6.tar.gz
  md5: 94ca029b1ff6975c305bd638d807e0ea
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - awesome-slugify = awesome-slugify:main
    #
    # Would create an entry point called awesome-slugify that calls awesome-slugify.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - regex
    - unidecode >=0.04.14,<0.05

  run:
    - python
    - regex
    - unidecode >=0.04.14,<0.05

test:
  # Python imports
  imports:
    - slugify

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dimka665/awesome-slugify
  license: GNU General Public License v3 (GPLv3)
  summary: 'Python flexible slugify function'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
