# pixi.toml file for developing pygnome
[workspace]
authors = ["Chris Barker <Chris.Barker@noaa.gov>",
           "NOAA GNOME team <orr.gnome@noaa.gov>"]
channels = ["https://prefix.dev/conda-forge"]
name = "PyGnome"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]


[dependencies]
python = ">=3.12,<3.14"

awesome-slugify = "*"
cfgrib = "*"
colander = "<2"
cornice = ">=3.4"
docutils = "*"
fiona = "*"
geojson = "*"
geopandas = "*"
# gitpython = "*"
gsw = "*"
htmlmin = "*"
jsmin = "*"
mapbox_earcut = "*"
netCDF4 = "*"
numpy = ">=2.5,<3"  #  works with numpy 1 and 2
pandas = "*"
paste = "*"
pastedeploy = ">=2.0"
progressbar = "*"
psutil = "*"
pyogrio = "*"
pyproj = "*"
python-dateutil = "*"
regex = "*"
scipy = "*"
shapely = ">=2.1.2"
trimesh = "*"
ujson = "*"

# NOAA maintained packages
gridded = ">=0.8,<0.9"
pynucos = ">=3.4.1"
cell_tree2d = ">=0.3.0"
py_gd = ">=2.3.3"
adios_db= ">=1.2.5"

[feature.build.dependencies]
cython  = ">=3"
pip = "*"
python-build = "*"
cmake = "*"
ninja = "*"
scikit-build-core = ">=0.9.9"
# rattler-build = "*"
setuptools-scm = ">=8"
# merging docs with build, the docs need a built install
# [feature.docs.dependencies]
sphinx = "*"
sphinx_rtd_theme = "*"
nbsphinx = "*"
sphinx-autoapi = "*"
sphinxcontrib-jquery = "*"


[feature.dev.dependencies]
ipython = "*"
ipdb = "*"
matplotlib = "*"
ruff = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-timeout = "*"
testfixtures = "*"

[feature.gridded-dev.dependencies]
# needed for gridded
cell_tree2d = ">=0.3"
cftime = "*"
# needed to build gridded
pip = "*"
python-build = "*"
hatch = ">=1.16.5"
hatch-vcs = "*"
# needed for gridded tests
pooch = ">=1.9.0,<2"

# you can only overide a conda dep with a conda dep :-(
# [feature.dev.override]
# numpy = ">=2.0.0" # Forces numpy to 2.0+ when 'dev' is active

# [feature.gridded-dev.pypi-dependencies]
# this only works if everyone use the same path
# On Chris' machine:
# gridded = { path = "../../../ERD-PythonPackages/gridded", editable = true }


# [feature.examples.dependencies]
# matplotlib = "*"
# xarray = "*"
# jupyter = "*"
# ipython = "*"


[feature.py312.dependencies]
python = "~=3.12.0"

[feature.py313.dependencies]
python = "~=3.13.0"

[environments]
default = { features = ["py312", "dev", "test", "build"], solve-group = "default" }
# using the oldest supported version for development
dev312 = ["py312", "dev", "test", "build"]
dev313 = ["py313", "dev", "test", "build"]
dev-gridded = ["gridded-dev", "py313", "dev", "test", "build"]
build312 = ["py312", "build"]
build313 = ["py313", "build"]
test312 = [ "py312", "test", "build" ]
test313 = [ "py313", "test", "build" ]
# docs = { features = ["py312", "docs"], solve-group = "default" }


[tasks]
install_edit = { cmd = "pip install --root-user-action=ignore --force-reinstall -e ./"}

build_wheel = {cmd = "python -m build --skip-dependency-check --no-isolation ./", default-environment = "build"}

install = { cmd = "pip install --root-user-action=ignore --force-reinstall --no-index --find-links=./dist/  gnome", depends-on = ["build_wheel"]}

test = { cmd = "pytest --runslow tests/unit_tests/", depends-on = ["install"]}

lint = { cmd = "ruff check gnome", default-environment = "dev"}

build_docs = { cmd = "cd documentation/ && make html", depends-on = ["install"], default-environment = "build" }

run_testing_scripts = {cmd = "python run_all.py", cwd = "scripts/testing_scripts"}

run_example_scripts = {cmd = "python run_all.py", cwd = "scripts/example_scripts"}

