#ifndef __EDITPROFILESDIALOG__
#define __EDITPROFILESDIALOG__
enum{
		EPOK=1,
		EPHILITEDDEFAULT,
		EPCANCEL,
		EPHELP,
		EPDELETEROWS_BTN,
		EPDELETEALL,
		EPREPLACE,
		EPDEPTHLABEL,
		EPDEPTH,
		EPDEPTHUNITS,
		EPU,
		EPV,
		EPTEMP,
		EPSAL,
		EPINCREMENT,
		
		EPDEPTH_LIST_LABEL,
		EPU_LIST_LABEL,
		EPTEMP_LIST_LABEL,
		EPSAL_LIST_LABEL,
	
		EPLIST,
		EPAUTOINCRTEXT=22,
		EPULABEL=25,
		EPAUTOINCRMETERS=27,

		EPVLABEL=30,
		EPTEMPUNITS=31,
		//EPBUTTONFRAME=47,
		EPFRAMEINPUT=38,
		EPV_LIST_LABEL=35,
		EPW_LIST_LABEL,
		//EPWLABEL,
		//EPW,
		EPVELUNITS=37,
		//EPDXDY = 45,
		//EPNUMCELLS
};


OSErr EditCDOGProfilesDialog(DepthValuesSetH *dvals,/*float *cellLength, long *numCells,*/ WindowPtr parentWindow);


enum{
		VARDISCHARGE_OK=1,
		VARDISCHARGE_HILITEDDEFAULT,
		VARDISCHARGE_CANCEL,
		VARDISCHARGE_HELP,
		VARDISCHARGE_DELETEROWS_BTN,
		VARDISCHARGE_DELETEALL,
		VARDISCHARGE_REPLACE,
		VARDISCHARGE_TIMELABEL,
		VARDISCHARGE_TIME,
		VARDISCHARGE_TIMEUNITS,
		CDOGSPILLDRPOPUPVAL,
		VARDISCHARGE_QGAS,
		VARDISCHARGE_TEMP,
		VARDISCHARGE_DIAM,
		VARDISCHARGE_INCREMENT,
		
		VARDISCHARGE_TIME_LIST_LABEL,
		VARDISCHARGE_QOIL_LIST_LABEL,
		VARDISCHARGE_TEMP_LIST_LABEL,
		VARDISCHARGE_RHOOIL_LIST_LABEL,
	
		VARDISCHARGE_LIST,
		VARDISCHARGE_AUTOINCRTEXT=21,
		CDOGSPILLDRPOPUP=22,
		VARDISCHARGE_AUTOINCRMETERS=25,

		VARDISCHARGE_QGAS_LABEL=26,
		TEMPUNITS_POPUP=27,
		DIAMETERUNITS_POPUP=28,
		DENSITYUNITS_POPUP=33,
		CDOGSPILLDRUNITSPOPUP=34,
		CDOGSPILLDRUNITSPOPUP2=60,
		//VARDISCHARGE_BUTTONFRAME=47,
		//VARDISCHARGE_FRAMEINPUT=35,
		GORUNITS_POPUP=59,
		VARDISCHARGE_FRAMEINPUT=61,
		VARDISCHARGE_FRAMEINPUT2=62,
		VARDISCHARGE_QGAS_LIST_LABEL=29,
		VARDISCHARGE_DIAM_LIST_LABEL,
		VARDISCHARGE_RHOOILLABEL,
		VARDISCHARGE_RHOOIL,
		VARDISCHARGE_RHOOILUNITS,
		//VARDISCHARGETYPE_POPUP=36,		
		VARDISCHARGETYPE_POPUP=35,		
	//	VARDISCHARGEDXDY = 45,
	//	VARDISCHARGENUMCELLS
	   CDOGSETTINGSEQLABEL, CDOGSETTINGSEQ, CDOGSETTINGSHYDDENSUNITS, 
	   CDOGSETTINGSRADLABEL, CDOGSETTINGSRAD, CDOGSETTINGSRADLABEL2, 
	   CDOGSETTINGSMOLWTLABEL, CDOGSETTINGSMOLWT,  
	   CDOGSETTINGSSEPLABEL, CDOGSETTINGSSEP,  
	   CDOGSETTINGSHYDDENSLABEL, CDOGSETTINGSHYDDENS, 
	   CDOGSETTINGSHYDPROCLABEL, CDOGSETTINGSHYDPROC, 
	   CDOGSETTINGSDROPSIZELABEL, CDOGSETTINGSDROPSIZE, CDOGSETTINGSMOLWTUNITS,
		GASYESNO_POPUP, GASYESNOLABEL, VARDISCHARGE_DURATIONLABEL, VARDISCHARGE_DURATION, 
		VARDISCHARGE_DURATIONUNITS, VARDISCHARGE_CONTINUOUS
};


OSErr CDOGVarDischargeDialog(DischargeDataH *dvals,Boolean *hydrogenSulfide,CDOGUserUnits *userUnits,CDOGParameters *spillParameters, CDOGSpillParameters *sCDOGSpillParameters2,WindowPtr parentWindow);
#endif