name: Pixi Tests

on: [push, pull_request]

jobs:

  tests:
    name: Test ${{ matrix.environment }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, windows-latest, ubuntu-latest]
        environment: [ test312, test313 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7

    - name: Set up Pixi Environment
      uses: prefix-dev/setup-pixi@v0.10.1
      with:
        cache: true
        manifest-path: py_gnome/pixi.toml
        environments: ${{ matrix.environment }}

    - name: Run Tests
      working-directory: py_gnome
      run: pixi run -e ${{ matrix.environment }} test
